### ISSUE TITLE
Bug: Index restore view=True does not work for shared user index

### ISSUE THREAD

**Issue by sef43** [unum-cloud/USearch#442]
### Describe the bug

If I try and do Index.restore(, view=True) on an index file created by a different user I get an error:
```
Traceback (most recent call last):
  File "/home/sfarr_test/test_load.py", line 5, in <module>
    index=Index.restore('test.index', view=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sfarr_test/usearch/lib/python3.11/site-packages/usearch/index.py", line 604, in restore
    index.view(path_or_buffer)
  File "/home/sfarr_test/usearch/lib/python3.11/site-packages/usearch/index.py", line 975, in view
    self._compiled.view_index_from_path(os.fspath(path_or_buffer), progress)
RuntimeError: Operation not permitted
```

### Steps to reproduce

with user 1:
```
import numpy as np
from usearch.index import Index

index = Index(ndim=4)


vectors = np.random.random(size=(100,4))

index.add(list(range(len(vectors))), vectors)

print(index)
index.save('test.index')
```

with user 2:
```
import numpy as np
from usearch.index import Index


index=Index.restore('test.index', view=True)
print(index)
```

### Expected behavior

The index should restore for user2 if view=True. It only restores properly if I change to view=False

### USearch version

 2.11.7

### Operating System

Ubuntu 22.04

### Hardware architecture

x86

### Which interface are you using?

Python bindings

### Are you open to being tagged as a contributor?

- [X] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
That sounds like a file permissions issue unrelated to USearch. Can you try creating and reading an arbitrary text file? Or simply checking file permissions?

**Comment by sef43** [comment]
Yes that is my main thought, I have checked this as much as possible. If I use Index.restore('test.index') it loads sucessfully. It is only when I try and use `view=True` where there is the error. There are no permission errors for other file operations. I am wondering if it is something related to the memory mapping settings.

**Comment by ashvardanian** [comment]
@sef43 shouldn't be a permissions issue on Ubuntu. Could have been on Mac or Windows. Is it still bothering you?

**Comment by sirfz** [comment]
Indeed, if tried to restore (with `view=True`) with a different user (on Ubuntu), I'm getting this exact error (Operation not permitted).

**Comment by ashvardanian** [comment]
@sirfz, that doesn’t sound like a USearch issue… more like a general permission management issue on Linux. Can you check the file permissions?

**Comment by sirfz** [comment]
The file has rw permissions enabled and even though the other user belongs to the group, it crashed until I chowned the file to that user.
